[package]
edition = "2018"
name = "distrack"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cocoa = "0.24.0"
objc = "0.2.7"
thiserror = "1.0.29"
url = "2.2.2"
